export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface Cue {
  start: number;
  end: number;
  text: string;
}

export type SubtitleFormat = "srt" | "vtt" | "txt";

export type TranslationMode = "translation" | "bilingual";

export interface Session {
  token: string;
  email: string;
}
