import type { CaptionTrack, Cue } from "../types";

export function getVideoId(url: string): string | null {
  const u = new URL(url);
  if (u.hostname === "www.youtube.com" || u.hostname === "youtube.com") {
    if (u.pathname === "/watch") return u.searchParams.get("v");
    if (u.pathname.startsWith("/shorts/")) return u.pathname.split("/")[2] ?? null;
  }
  return null;
}

export async function fetchCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const res = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    credentials: "same-origin",
  });
  const html = await res.text();
  const match = html.match(/"captionTracks":(\[.*?\])(?=,"(?:audioTracks|translationLanguages)")/);
  if (!match) return [];

  const raw = JSON.parse(match[1]) as Array<{
    baseUrl: string;
    languageCode: string;
    name?: { simpleText?: string; runs?: Array<{ text: string }> };
    kind?: string;
  }>;

  return raw.map((track) => ({
    baseUrl: track.baseUrl,
    languageCode: track.languageCode,
    name: track.name?.simpleText ?? track.name?.runs?.map((r) => r.text).join("") ?? track.languageCode,
    isAutoGenerated: track.kind === "asr",
  }));
}

// Strips non-speech annotations auto-generated captions commonly include,
// e.g. "[music]", "[аплодисменты]", "(smiles)". Applied to every format.
const ANNOTATION_PATTERN = /[[(][^\])]*[\])]/g;

export function cleanupCues(cues: Cue[]): Cue[] {
  return cues
    .map((cue) => ({
      ...cue,
      text: cue.text.replace(ANNOTATION_PATTERN, "").replace(/\s+/g, " ").trim(),
    }))
    .filter((cue) => cue.text.length > 0);
}

function formatTimestamp(seconds: number, decimalSeparator: "," | "."): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.round((seconds - Math.floor(seconds)) * 1000);
  const pad = (n: number, len = 2) => String(n).padStart(len, "0");
  return `${pad(h)}:${pad(m)}:${pad(s)}${decimalSeparator}${pad(ms, 3)}`;
}

export function toSRT(cues: Cue[]): string {
  return cues
    .map((cue, i) => {
      const start = formatTimestamp(cue.start, ",");
      const end = formatTimestamp(cue.end, ",");
      return `${i + 1}\n${start} --> ${end}\n${cue.text}\n`;
    })
    .join("\n");
}

export function toVTT(cues: Cue[]): string {
  const body = cues
    .map((cue) => {
      const start = formatTimestamp(cue.start, ".");
      const end = formatTimestamp(cue.end, ".");
      return `${start} --> ${end}\n${cue.text}\n`;
    })
    .join("\n");
  return `WEBVTT\n\n${body}`;
}

export function toTXT(cues: Cue[]): string {
  return cues.map((c) => c.text).join("\n");
}

export function serializeCues(cues: Cue[], format: "srt" | "vtt" | "txt"): string {
  if (format === "srt") return toSRT(cues);
  if (format === "vtt") return toVTT(cues);
  return toTXT(cues);
}
